// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8ppfvEJUfPiivNtYNTK4f5nR9YxuQ50',
    appId: '1:41718740059:web:b040131e962ec5b4c5fb7e',
    messagingSenderId: '41718740059',
    projectId: 'circle-guide-519e4',
    authDomain: 'circle-guide-519e4.firebaseapp.com',
    storageBucket: 'circle-guide-519e4.appspot.com',
    measurementId: 'G-R11VKVGJND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa3VNUIjkGGZMVmkcpnuKE0enJAvw2jbk',
    appId: '1:41718740059:android:237dbb108ea875ccc5fb7e',
    messagingSenderId: '41718740059',
    projectId: 'circle-guide-519e4',
    storageBucket: 'circle-guide-519e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vlgQMLxNYO1M2mGWC_YYwRSW4yXpb6o',
    appId: '1:41718740059:ios:0272d888721436a7c5fb7e',
    messagingSenderId: '41718740059',
    projectId: 'circle-guide-519e4',
    storageBucket: 'circle-guide-519e4.appspot.com',
    iosBundleId: 'com.example.circleGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vlgQMLxNYO1M2mGWC_YYwRSW4yXpb6o',
    appId: '1:41718740059:ios:db963fa9f918a04ec5fb7e',
    messagingSenderId: '41718740059',
    projectId: 'circle-guide-519e4',
    storageBucket: 'circle-guide-519e4.appspot.com',
    iosBundleId: 'com.example.circleGuide.RunnerTests',
  );
}
